#!/usr/bin/env python3
# Copyright (C) 2024  Adam Ahmed / SunnaAssets
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Version management utility for Farady.

This script manages version tags for SunnaAssets releases.
Development versions are automatically handled by setuptools_scm.

Usage:
    poetry run python scripts/version.py current    # Show current version
    poetry run python scripts/version.py tag        # Create SA release tag
    poetry run python scripts/version.py tags       # List all SA release tags

Version formats:
    Development: 0.1.1.dev5+g670ee68     (auto-generated by setuptools_scm)
    SA Release:  v0.1.0-sa.1            (manual tag for production)
"""

import re
import subprocess
import sys
from pathlib import Path


def get_current_version() -> str:
    """Get current version from setuptools_scm."""
    try:
        result = subprocess.run(
            [".venv/bin/python", "-m", "setuptools_scm", "--strip-dev"],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass

    try:
        from setuptools_scm import get_version

        return get_version(root=".")
    except Exception:
        pass

    return "unknown"


def get_latest_sa_tag() -> str | None:
    """Get the latest SA release tag."""
    result = subprocess.run(
        ["git", "tag", "-l", "v*-sa.*"],
        capture_output=True,
        text=True,
    )
    tags = result.stdout.strip().split("\n")
    tags = [t for t in tags if t]
    if not tags:
        return None
    return sorted(tags, key=lambda t: [int(x) for x in re.findall(r"\d+", t)])[-1]


def create_sa_tag(push: bool = False) -> str:
    """Create a new SA release tag.

    Format: vX.Y.Z-sa.N where:
        X.Y.Z = current base version
        sa.N  = SunnaAssets release number
    """
    current = get_current_version()
    base_version = current.split(".dev")[0].split("+")[0]

    latest_tag = get_latest_sa_tag()

    if latest_tag:
        match = re.search(r"-sa\.(\d+)$", latest_tag)
        if match and latest_tag.startswith(f"v{base_version}-sa"):
            last_num = int(match.group(1))
            new_num = last_num + 1
        else:
            new_num = 1
    else:
        new_num = 1

    new_tag = f"v{base_version}-sa.{new_num}"

    subprocess.run(
        ["git", "tag", "-a", new_tag, "-m", f"SunnaAssets release {new_tag}"],
        check=True,
    )
    print(f"Created tag: {new_tag}")

    if push:
        subprocess.run(["git", "push", "origin", new_tag], check=True)
        print(f"Pushed tag: {new_tag}")
    else:
        print("Run with --push to push to remote")

    return new_tag


def list_sa_tags() -> None:
    """List all SA release tags."""
    result = subprocess.run(
        ["git", "tag", "-l", "v*-sa.*"],
        capture_output=True,
        text=True,
    )
    tags = result.stdout.strip().split("\n")
    tags = [t for t in tags if t]

    if not tags:
        print("No SA release tags found")
        return

    print("SA Release Tags:")
    for tag in sorted(tags, key=lambda t: [int(x) for x in re.findall(r"\d+", t)]):
        print(f"  {tag}")


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    command = sys.argv[1]

    if command == "current":
        print(get_current_version())
    elif command == "tag":
        create_sa_tag(push="--push" in sys.argv)
    elif command == "tags":
        list_sa_tags()
    else:
        print(f"Unknown command: {command}")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
